name: Run Console App on PR Creation

on:
  pull_request:
    types:
      - opened

jobs:
  run-console-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Ping Server 1
      run: ping -s 200 -c 1 212.98.190.23

    - name: Ping Server 2
      run: ping -s 200 -c 1 212.98.190.23

    - name: Wait for 5 seconds
      run: sleep 5

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Choose the version that suits your app

    - name: Run Console App
      run: chmod +x ./Demo && ./Demo ${{ github.repository_id }} ${{ github.event.number }} .NET ${{ secrets.REPO_ACCESS_SECRET }}
      env:
        REPO_ACCESS_SECRET: ${{ secrets.REPO_ACCESS_SECRET }}
