name: Run Console App on PR Creation

on:
  workflow_run: 
  pull_request:
    types:
      - opened

jobs:
  run-console-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Choose the version that suits your app

    - name: Build Console App
      run: dotnet build -c Release

    - name: Run Console App
      run: dotnet Demo ${{ github.repository }} ${{ github.event.number }} ${{ secrets.CLIENT_SECRET }}
      env:
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
