name: Run Console App on PR Creation

on:
  pull_request:
    types:
      - opened

jobs:
  run-console-app:
    runs-on: 
      -self-hosted
      -llm-runner-1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Console App
      run: .\Demo.exe ${{ github.repository_id }} ${{ github.event.number }} .NET ${{ secrets.REPO_ACCESS_SECRET }} http://212.98.190.23:5001
      env:
        REPO_ACCESS_SECRET: ${{ secrets.REPO_ACCESS_SECRET }}
