name: PR File Content Base64 Logger

on:
  pull_request:
    types:
      - opened

jobs:
  log-pr-files-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Env
      run: env

    - name: Log PR files content
      run: |
        for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
          echo "Processing file: $file"
          content=$(cat $file | base64)
          echo "Base64 content of $file:"
          echo "$content"
        done
