name: Run Console App on PR Creation

on:
  pull_request:
    types:
      - opened

jobs:
  run-console-app:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Console App
      run: .\Demo.exe ${{ github.repository_id }} ${{ github.event.number }} .NET ${{ secrets.GITHUB_TOKEN }} http://localhost:5001
